version: 0.2
env:
  secrets-manager:
    GITHUB_TOKEN: devminnu_github_token:GITHUB_TOKEN

phases:
  pre_build:
    commands:
      - go version
      - git config --global url."https://$GITHUB_TOKEN@github.com".insteadOf "https://github.com"
      - ACCOUNT_ID=$(aws sts get-caller-identity --output text --query 'Account')
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/product-service
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - echo build started on `date`
      - docker version
      - docker build --build-arg GITHUB_TOKEN=$GITHUB_TOKEN --build-arg ACCOUNT_ID=$ACCOUNT_ID -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo build completed on `date`
      - docker push $REPOSITORY_URI:latest
      - echo writing image definition file ...
      - printf '[{"name":"quote-service","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
