version: "3.9"

services:
  # postgres:
  #   image: "postgres"
  #   ports:
  #     - "5432:5432"
  #   restart: always
  #   env_file: .env/postgres.env
  #   volumes:
  #     - ./scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  # mognodb:
  #   image: mongo
  #   restart: always
  #   env_file: .env/mongo.env
  product:
    build: .
    ports:
      - "8080:8080"
      - "50051:50051"
    restart: always
    # depends_on:
    #   - postgres
    env_file: .env/product.env
